name: Verificar API Online

on:
  schedule:
    - cron: "*/15 * * * *"  
  workflow_dispatch:       
  push:
    branches:
      - main              

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar status da API
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://trabalhorpa-api.onrender.com/docs
          max-attempts: 3
          retry-delay: 5
          retry-all: true
